-- MySQL Script generated by MySQL Workbench
-- Sun Mar 15 20:33:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MallMAP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MallMAP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MallMAP` DEFAULT CHARACTER SET utf8 ;
USE `MallMAP` ;

-- -----------------------------------------------------
-- Table `MallMAP`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`Role` (
  `RoleID` INT NOT NULL AUTO_INCREMENT,
  `RoleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RoleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `RoleID` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UersID_UNIQUE` (`UserID` ASC) VISIBLE,
  UNIQUE INDEX `UsersName_UNIQUE` (`UserName` ASC) VISIBLE,
  INDEX `fk_Users_Role1_idx` (`RoleID` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Role1`
    FOREIGN KEY (`RoleID`)
    REFERENCES `MallMAP`.`Role` (`RoleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`StoreCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`StoreCategory` (
  `StoreCategoryID` INT NOT NULL AUTO_INCREMENT,
  `StoreCategoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StoreCategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`Mall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`Mall` (
  `MallID` INT NOT NULL AUTO_INCREMENT,
  `Mallname` VARCHAR(255) NOT NULL,
  `Location` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`MallID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`Floor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`Floor` (
  `FloorID` INT NOT NULL AUTO_INCREMENT,
  `FloorName` VARCHAR(45) NOT NULL,
  `MallID` INT NOT NULL,
  `MapImageURL` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`FloorID`),
  INDEX `fk_floor_Mall1_idx` (`MallID` ASC) VISIBLE,
  CONSTRAINT `fk_floor_Mall1`
    FOREIGN KEY (`MallID`)
    REFERENCES `MallMAP`.`Mall` (`MallID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`Store` (
  `StoreID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `StoreName` VARCHAR(255) NOT NULL,
  `StoreCategoryName` VARCHAR(255) NOT NULL,
  `StoreCategoryIcon` VARCHAR(20) NOT NULL,
  `StoreCategoryID` INT NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `LogoURL` VARCHAR(255) NOT NULL,

  `MallID` INT NOT NULL,

  `FloorName`VARCHAR(100) NOT NULL,
  `FloorID`VARCHAR(30) NOT NULL,
  `PosX` FLOAT NOT NULL,
  `PosY` FLOAT NOT NULL,

  PRIMARY KEY (`StoreID`),

  INDEX `fk_Store_User1_idx` (`UserID` ASC),
  INDEX `fk_Store_StoreCategory1_idx` (`StoreCategoryID` ASC),
  INDEX `fk_Store_floor1_idx` (`FloorID` ASC),
  INDEX `fk_Store_mall1_idx` (`MallID` ASC),

  CONSTRAINT `fk_Store_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `MallMAP`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_Store_StoreCategory1`
    FOREIGN KEY (`StoreCategoryID`)
    REFERENCES `MallMAP`.`StoreCategory` (`StoreCategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_Store_floor1`
    FOREIGN KEY (`FloorID`)
    REFERENCES `MallMAP`.`Floor` (`FloorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_Store_Mall1`
    FOREIGN KEY (`MallID`)
    REFERENCES `MallMAP`.`Mall` (`MallID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION

) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`ProductCategory` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`Product` (
  `ProductID` INT NOT NULL AUTO_INCREMENT,
  `ProductName` VARCHAR(255) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `StockQuantity` INT NOT NULL,
  `ProductImageURL` VARCHAR(255) NOT NULL,
  `StoreID` INT NOT NULL,
  `CategoryID` INT NOT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ProductID`),
  INDEX `fk_Product_Category1_idx` (`CategoryID` ASC) VISIBLE,
  INDEX `fk_Product_Store1_idx` (`StoreID` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `MallMAP`.`Category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Store1`
    FOREIGN KEY (`StoreID`)
    REFERENCES `MallMAP`.`Store` (`StoreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`FavoriteStore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`FavoriteStore` (
  `FavoriteStoreID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `StoreID` INT NOT NULL,
  PRIMARY KEY (`FavoriteStoreID`),
  INDEX `fk_FavoriteStore_User1_idx` (`UserID` ASC) VISIBLE,
  INDEX `fk_FavoriteStore_Store1_idx` (`StoreID` ASC) VISIBLE,
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE,
  UNIQUE INDEX `StoreID_UNIQUE` (`StoreID` ASC) VISIBLE,
  CONSTRAINT `fk_FavoriteStore_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `MallMAP`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FavoriteStore_Store1`
    FOREIGN KEY (`StoreID`)
    REFERENCES `MallMAP`.`Store` (`StoreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`FavoriteProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`FavoriteProduct` (
  `FavoriteProductID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  PRIMARY KEY (`FavoriteProductID`),
  INDEX `fk_FavoriteProduct_User1_idx` (`UserID` ASC) VISIBLE,
  INDEX `fk_FavoriteProduct_Product1_idx` (`ProductID` ASC) VISIBLE,
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE,
  UNIQUE INDEX `ProductID_UNIQUE` (`ProductID` ASC) VISIBLE,
  CONSTRAINT `fk_FavoriteProduct_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `MallMAP`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FavoriteProduct_Product1`
    FOREIGN KEY (`ProductID`)
    REFERENCES `MallMAP`.`Product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
