-- MySQL Script generated by MySQL Workbench
-- Sat Mar 14 19:04:43 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MallMAP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MallMAP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MallMAP` DEFAULT CHARACTER SET utf8 ;
USE `MallMAP` ;

-- -----------------------------------------------------
-- Table `MallMAP`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`Role` (
  `RoleID` INT NOT NULL AUTO_INCREMENT,
  `RoleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RoleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(255) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `RoleID` INT NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UersID_UNIQUE` (`UserID` ASC) VISIBLE,
  UNIQUE INDEX `UsersName_UNIQUE` (`UserName` ASC) VISIBLE,
  INDEX `fk_Users_Role1_idx` (`RoleID` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Role1`
    FOREIGN KEY (`RoleID`)
    REFERENCES `MallMAP`.`Role` (`RoleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`StoreCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`StoreCategory` (
  `StoreCategoryID` INT NOT NULL AUTO_INCREMENT,
  `StoreCategoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StoreCategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`Store` (
  `StoreID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `StoreName` VARCHAR(255) NOT NULL,
  `StoreCategoryID` INT NOT NULL,
  `Phone` VARCHAR(20) NOT NULL,
  `LogoURL` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`StoreID`),
  UNIQUE INDEX `StoreID_UNIQUE` (`StoreID` ASC) VISIBLE,
  INDEX `fk_Store_StoreCategory1_idx` (`StoreCategoryID` ASC) VISIBLE,
  INDEX `fk_Store_User1_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `fk_Store_StoreCategory1`
    FOREIGN KEY (`StoreCategoryID`)
    REFERENCES `MallMAP`.`StoreCategory` (`StoreCategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Store_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `MallMAP`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`Category` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MallMAP`.`Product` (
  `ProductID` INT NOT NULL AUTO_INCREMENT,
  `ProductName` VARCHAR(255) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `StockQuantity` INT NOT NULL,
  `ProductImageURL` VARCHAR(255) NOT NULL,
  `StoreID` INT NOT NULL,
  `CategoryID` INT NOT NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `fk_Product_Category1_idx` (`CategoryID` ASC) VISIBLE,
  INDEX `fk_Product_Store1_idx` (`StoreID` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `MallMAP`.`Category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Store1`
    FOREIGN KEY (`StoreID`)
    REFERENCES `MallMAP`.`Store` (`StoreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Sample Data
-- -----------------------------------------------------
INSERT INTO `MallMAP`.`Role` (`RoleName`) VALUES
  ('SuperAdmin'),
  ('StoreOwner'),
  ('Customer');

INSERT INTO `MallMAP`.`User` (`UserName`, `PasswordHash`, `RoleID`) VALUES
  ('admin1', 'hash_admin1', 1),
  ('storeOwner1', 'hash_storeOwner1', 2),
  ('customer1', 'hash_customer1', 3);

INSERT INTO `MallMAP`.`StoreCategory` (`StoreCategoryName`) VALUES
  ('Food'),
  ('Fashion'),
  ('Electronics');

INSERT INTO `MallMAP`.`Store` (`UserID`, `StoreName`, `StoreCategoryID`, `Phone`, `LogoURL`) VALUES
  (2, 'Yamazaki', 1, '0912345678', 'http://example.com/logoA.png'),
  (2, 'ElectroWorld', 3, '0987654321', 'http://example.com/logoB.png');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
