-- MySQL Script generated by MySQL Workbench
-- Sun Mar 15 20:33:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MallMAP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MallMAP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mallmap` DEFAULT CHARACTER SET utf8 ;
USE `mallmap` ;

-- -----------------------------------------------------
-- Table `MallMAP`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mallmap`.`Role` (
  `RoleID` INT NOT NULL AUTO_INCREMENT,
  `RoleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RoleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mallmap`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `RoleID` INT NOT NULL,
  `StoreID` INT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UsersName_UNIQUE` (`UserName` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  INDEX `fk_Users_Role1_idx` (`RoleID` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Role1`
    FOREIGN KEY (`RoleID`) 
    REFERENCES `mallmap`.`Role` (`RoleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`StoreCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mallmap`.`StoreCategory` (
  `StoreCategoryID` INT NOT NULL AUTO_INCREMENT,
  `StoreCategoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StoreCategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`Mall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mallmap`.`Mall` (
  `MallID` INT NOT NULL AUTO_INCREMENT,
  `Mallname` VARCHAR(255) NOT NULL,
  `Location` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`MallID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`Floor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mallmap`.`Floor` (
  `FloorID` INT NOT NULL AUTO_INCREMENT,
  `FloorName` VARCHAR(45) NOT NULL,
  `MallID` INT NOT NULL,
  `MapImageURL` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`FloorID`),
  INDEX `fk_floor_Mall1_idx` (`MallID` ASC) VISIBLE,
  CONSTRAINT `fk_floor_Mall1`
    FOREIGN KEY (`MallID`)
    REFERENCES `mallmap`.`Mall` (`MallID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mallmap`.`Store` (
  `StoreID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `StoreName` VARCHAR(255) NOT NULL,
  `StoreCategoryID` INT NOT NULL,
  `Phone` VARCHAR(20) NOT NULL,
  `LogoURL` VARCHAR(255) NOT NULL,
  `FloorID` INT NOT NULL,
  `PosX` FLOAT NOT NULL,
  `PosY` FLOAT NOT NULL,
  `OpeningHours` VARCHAR(100) NULL,
  PRIMARY KEY (`StoreID`),
  INDEX `fk_Store_StoreCategory1_idx` (`StoreCategoryID` ASC) VISIBLE,
  INDEX `fk_Store_User1_idx` (`UserID` ASC) VISIBLE,
  INDEX `fk_Store_floor1_idx` (`FloorID` ASC) VISIBLE,
  CONSTRAINT `fk_Store_StoreCategory1`
    FOREIGN KEY (`StoreCategoryID`)
    REFERENCES `mallmap`.`StoreCategory` (`StoreCategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Store_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `mallmap`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Store_floor1`
    FOREIGN KEY (`FloorID`)
    REFERENCES `mallmap`.`Floor` (`FloorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mallmap`.`Category` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mallmap`.`Product` (
  `ProductID` INT NOT NULL AUTO_INCREMENT,
  `ProductName` VARCHAR(255) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `StockQuantity` INT NOT NULL,
  `ProductImageURL` VARCHAR(255) NOT NULL,
  `StoreID` INT NOT NULL,
  `CategoryID` INT NOT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ProductID`),
  INDEX `fk_Product_Category1_idx` (`CategoryID` ASC) VISIBLE,
  INDEX `fk_Product_Store1_idx` (`StoreID` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `mallmap`.`Category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Store1`
    FOREIGN KEY (`StoreID`)
    REFERENCES `mallmap`.`Store` (`StoreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`FavoriteStore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mallmap`.`FavoriteStore` (
  `FavoriteStoreID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `StoreID` INT NOT NULL,
  PRIMARY KEY (`FavoriteStoreID`),
  INDEX `fk_FavoriteStore_User1_idx` (`UserID` ASC) VISIBLE,
  INDEX `fk_FavoriteStore_Store1_idx` (`StoreID` ASC) VISIBLE,
  CONSTRAINT `fk_FavoriteStore_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `mallmap`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FavoriteStore_Store1`
    FOREIGN KEY (`StoreID`)
    REFERENCES `mallmap`.`Store` (`StoreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MallMAP`.`FavoriteProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mallmap`.`FavoriteProduct` (
  `FavoriteProductID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  PRIMARY KEY (`FavoriteProductID`),
  INDEX `fk_FavoriteProduct_User1_idx` (`UserID` ASC) VISIBLE,
  INDEX `fk_FavoriteProduct_Product1_idx` (`ProductID` ASC) VISIBLE,
  CONSTRAINT `fk_FavoriteProduct_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `mallmap`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FavoriteProduct_Product1`
    FOREIGN KEY (`ProductID`)
    REFERENCES `mallmap`.`Product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
